/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * crearCuenta.java
 *
 * Created on Nov 7, 2012, 4:50:30 PM
 */
package EDJC.ventanas;

import EDJC.seguridad.Usuario;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;


/**
 *
 * @author Edgardo Castellanos
 */
public class crearCuenta extends javax.swing.JFrame {
    ArrayList<Usuario> usuarios=new ArrayList<>();
    
    
    

    /** Creates new form crearCuenta */
    public crearCuenta() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jbCrear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24));
        jLabel1.setText("Crear Cuenta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 146, 35);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 80, 100, 29);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(130, 110, 170, 30);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18));
        jLabel3.setText("Nombre Completo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 160, 170, 30);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(130, 190, 170, 30);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel4.setText("Confirmar Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 320, 180, 30);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(130, 270, 170, 30);

        jbCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCrear.setText("Crear");
        jbCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearActionPerformed(evt);
            }
        });
        getContentPane().add(jbCrear);
        jbCrear.setBounds(150, 420, 130, 40);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 240, 110, 30);
        getContentPane().add(txtPassword2);
        txtPassword2.setBounds(130, 360, 170, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-448)/2, (screenSize.height-520)/2, 448, 520);
    }// </editor-fold>//GEN-END:initComponents

private void jbCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearActionPerformed
// TODO add your handling code here:
    Usuario ut=new Usuario(this.txtUsername.getText(),this.txtPassword.getPassword());
    //for(Usuario u: usuarios){
        if(Arrays.equals(txtPassword2.getPassword(), ut.getPassword())){
            
    if(usuarios.isEmpty()){
        usuarios.add(new Usuario(ut.getUsername(),ut.getPassword()));
            setDefaultCloseOperation(crearCuenta.HIDE_ON_CLOSE);
            setVisible(false); 
            txtUsername.setText("");
            txtNombre.setText("");
            txtPassword.setText("");
            
        }
    else {
    
    for(Usuario us: usuarios){
        if(us.equals(ut))
            JOptionPane.showMessageDialog(this, "Usuario Ya Existente","Error",JOptionPane.ERROR_MESSAGE);
 
        else{
            usuarios.add(new Usuario(ut.getUsername(),ut.getPassword()));
            setDefaultCloseOperation(crearCuenta.HIDE_ON_CLOSE);
            setVisible(false); 
            txtUsername.setText("");
            txtNombre.setText("");
            txtPassword.setText("");
            
        }
    }
    }
        }else
            JOptionPane.showMessageDialog(this, "Contraseña Incorrecta","Warning",JOptionPane.WARNING_MESSAGE);
  //  }
}//GEN-LAST:event_jbCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new crearCuenta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCrear;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
