/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuAdministrador.java
 *
 * Created on Nov 10, 2012, 12:03:04 PM
 */
package EDJC.ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author Edgardo Castellanos
 */
public class MenuAdministrador extends javax.swing.JFrame {
    TipoSala t=new TipoSala();
    AgregarPelicula p=new AgregarPelicula();

    /** Creates new form MenuAdministrador */
    public MenuAdministrador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb4 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        jbIngresar = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido Administrador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 10, 290, 30);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setText("4. Editar Datos de Perfil");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 320, 210, 40);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel3.setText("1. Agregar Sala de Cine");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 190, 40);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel4.setText("2. Agregar Película");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 180, 40);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel5.setText("3. Editar Horarios");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 250, 180, 40);

        cb4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb4StateChanged(evt);
            }
        });
        getContentPane().add(cb4);
        cb4.setBounds(280, 330, 21, 21);

        cb1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb1StateChanged(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(280, 110, 21, 21);

        cb2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb2StateChanged(evt);
            }
        });
        getContentPane().add(cb2);
        cb2.setBounds(280, 180, 21, 21);

        cb3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb3StateChanged(evt);
            }
        });
        getContentPane().add(cb3);
        cb3.setBounds(280, 260, 21, 21);

        jbIngresar.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jbIngresar.setText("Ingresar");
        jbIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jbIngresar);
        jbIngresar.setBounds(150, 400, 120, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-438)/2, (screenSize.height-494)/2, 438, 494);
    }// </editor-fold>//GEN-END:initComponents

private void jbIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIngresarActionPerformed
// TODO add your handling code here:
 
    
     if(this.cb1.isSelected()){
        JOptionPane.showMessageDialog(this, "Agregar Sala de Cine","Bien hecho",JOptionPane.INFORMATION_MESSAGE);
        t.setVisible(true);
        return;
    }
    else if(this.cb2.isSelected()){
        JOptionPane.showMessageDialog(this, "Agregar Pelicula","Bien hecho",JOptionPane.INFORMATION_MESSAGE);
        p.setVisible(true);
        return;
    }
    else if(this.cb3.isSelected()){
        JOptionPane.showMessageDialog(this, "Editar Horarios","Bien hecho",JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    else if(this.cb4.isSelected()){
        JOptionPane.showMessageDialog(this, "Editar Datos de Perfil","Bien hecho",JOptionPane.INFORMATION_MESSAGE);
        return;
    }
}//GEN-LAST:event_jbIngresarActionPerformed

private void cb1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb1StateChanged
// TODO add your handling code here:
    if(this.cb1.isSelected()){
        this.cb2.setSelected(false);
        this.cb3.setSelected(false);
        this.cb4.setSelected(false);
    }
}//GEN-LAST:event_cb1StateChanged

private void cb2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb2StateChanged
// TODO add your handling code here:
     if(this.cb2.isSelected()){
        this.cb1.setSelected(false);
        this.cb3.setSelected(false);
        this.cb4.setSelected(false);
    }
}//GEN-LAST:event_cb2StateChanged

private void cb3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb3StateChanged
// TODO add your handling code here:
     if(this.cb3.isSelected()){
        this.cb1.setSelected(false);
        this.cb2.setSelected(false);
        this.cb4.setSelected(false);
    }
}//GEN-LAST:event_cb3StateChanged

private void cb4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb4StateChanged
// TODO add your handling code here:
     if(this.cb4.isSelected()){
        this.cb2.setSelected(false);
        this.cb3.setSelected(false);
        this.cb1.setSelected(false);
    }
}//GEN-LAST:event_cb4StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbIngresar;
    // End of variables declaration//GEN-END:variables
}
