/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TipoSala.java
 *
 * Created on Nov 12, 2012, 3:06:24 PM
 */
package EDJC.ventanas;

/**
 *
 * @author Edgardo Castellanos
 */
public class TipoSala extends javax.swing.JFrame {

    /** Creates new form TipoSala */
    public TipoSala() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb2 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        jbAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel1.setText("Sala 3D");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 150, 110, 40);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de Sala");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 10, 110, 40);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel3.setText("Sala 2D");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 70, 110, 40);

        cb2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb2StateChanged(evt);
            }
        });
        getContentPane().add(cb2);
        cb2.setBounds(210, 160, 21, 21);

        cb1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb1StateChanged(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(210, 80, 21, 21);

        jbAgregar.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jbAgregar.setText("Agregar");
        getContentPane().add(jbAgregar);
        jbAgregar.setBounds(120, 230, 110, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-377)/2, (screenSize.height-346)/2, 377, 346);
    }// </editor-fold>//GEN-END:initComponents

private void cb1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb1StateChanged
// TODO add your handling code here:
    if(this.cb1.isSelected())
        this.cb2.setSelected(false);
}//GEN-LAST:event_cb1StateChanged

private void cb2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb2StateChanged
// TODO add your handling code here:
    if(this.cb2.isSelected())
        this.cb1.setSelected(false);
}//GEN-LAST:event_cb2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TipoSala().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAgregar;
    // End of variables declaration//GEN-END:variables
}
