/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AgregarPelicula.java
 *
 * Created on Nov 12, 2012, 3:38:56 PM
 */
package EDJC.gui;

import EDJC.peliculas.GeneroPelicula;
import EDJC.peliculas.Pelicula;
import EDJC.peliculas.Pelicula2D;
import EDJC.peliculas.Pelicula3D;
import EDJC.peliculas.TipoClasificacion;
import EDJC.peliculas.TipoPelicula;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Edgardo Castellanos
 */
public class AgregarPelicula extends javax.swing.JFrame {
    ArrayList<Pelicula> peliculas;
    private int duracion;
    private String nombre;
    private GeneroPelicula genero;
    private TipoClasificacion clas;
    private TipoPelicula tipo;

    /** Creates new form AgregarPelicula */
    public AgregarPelicula() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    AgregarPelicula(ArrayList<Pelicula> pelis) {
        peliculas = pelis;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        rdAdultos = new javax.swing.JRadioButton();
        rdAnimada = new javax.swing.JRadioButton();
        rdDrama = new javax.swing.JRadioButton();
        rdAccion = new javax.swing.JRadioButton();
        rdMusical = new javax.swing.JRadioButton();
        rdDocumental = new javax.swing.JRadioButton();
        rdComedia = new javax.swing.JRadioButton();
        rdTodos = new javax.swing.JRadioButton();
        rd18 = new javax.swing.JRadioButton();
        rd15 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cb2D = new javax.swing.JCheckBox();
        cb3D = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setText("Pelicula");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 120, 30);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de Película");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 350, 200, 30);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel3.setText("Duracion de la Pelicula");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 200, 30);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel4.setText("Nombre de la Pelicula");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 200, 30);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel5.setText("Genero de la Pelicula");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 190, 200, 30);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(290, 120, 130, 30);
        getContentPane().add(txtDuracion);
        txtDuracion.setBounds(290, 70, 130, 30);

        rdAdultos.setText("Adultos");
        rdAdultos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdAdultosStateChanged(evt);
            }
        });
        getContentPane().add(rdAdultos);
        rdAdultos.setBounds(390, 300, 100, 23);

        rdAnimada.setText("Animada");
        rdAnimada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdAnimadaStateChanged(evt);
            }
        });
        getContentPane().add(rdAnimada);
        rdAnimada.setBounds(270, 190, 90, 23);

        rdDrama.setText("Drama");
        rdDrama.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdDramaStateChanged(evt);
            }
        });
        getContentPane().add(rdDrama);
        rdDrama.setBounds(270, 210, 90, 23);

        rdAccion.setText("Acción");
        rdAccion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdAccionStateChanged(evt);
            }
        });
        getContentPane().add(rdAccion);
        rdAccion.setBounds(270, 230, 90, 23);

        rdMusical.setText("Musical");
        rdMusical.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdMusicalStateChanged(evt);
            }
        });
        getContentPane().add(rdMusical);
        rdMusical.setBounds(390, 190, 100, 23);

        rdDocumental.setText("Documental");
        rdDocumental.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdDocumentalStateChanged(evt);
            }
        });
        getContentPane().add(rdDocumental);
        rdDocumental.setBounds(390, 210, 100, 23);

        rdComedia.setText("Comedia");
        rdComedia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdComediaStateChanged(evt);
            }
        });
        getContentPane().add(rdComedia);
        rdComedia.setBounds(390, 230, 100, 23);

        rdTodos.setText("Todo Público");
        rdTodos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdTodosStateChanged(evt);
            }
        });
        getContentPane().add(rdTodos);
        rdTodos.setBounds(270, 280, 110, 23);

        rd18.setText("Mayores de 18");
        rd18.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rd18StateChanged(evt);
            }
        });
        getContentPane().add(rd18);
        rd18.setBounds(270, 300, 120, 23);

        rd15.setText("Mayores de 15");
        rd15.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rd15StateChanged(evt);
            }
        });
        getContentPane().add(rd15);
        rd15.setBounds(390, 280, 110, 23);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel6.setText("Clasificación");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 280, 200, 30);

        cb2D.setText("2D");
        cb2D.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb2DStateChanged(evt);
            }
        });
        getContentPane().add(cb2D);
        cb2D.setBounds(270, 350, 39, 23);

        cb3D.setText("3D");
        cb3D.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cb3DStateChanged(evt);
            }
        });
        getContentPane().add(cb3D);
        cb3D.setBounds(270, 380, 39, 23);

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 440, 140, 40);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-547)/2, (screenSize.height-527)/2, 547, 527);
    }// </editor-fold>//GEN-END:initComponents

private void rdAnimadaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdAnimadaStateChanged
// TODO add your handling code here:
    if(this.rdAnimada.isSelected()){
        this.rdAccion.setSelected(false);
        this.rdComedia.setSelected(false);
        this.rdDocumental.setSelected(false);
        this.rdDrama.setSelected(false);
        this.rdMusical.setSelected(false);
        this.genero = GeneroPelicula.ANIMADA;
    }
        
}//GEN-LAST:event_rdAnimadaStateChanged

private void rdDramaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdDramaStateChanged
// TODO add your handling code here:
    if(this.rdDrama.isSelected()){
        this.rdAccion.setSelected(false);
        this.rdComedia.setSelected(false);
        this.rdDocumental.setSelected(false);
        this.rdAnimada.setSelected(false);
        this.rdMusical.setSelected(false);
        this.genero = GeneroPelicula.DRAMA;
    }
}//GEN-LAST:event_rdDramaStateChanged

private void rdAccionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdAccionStateChanged
// TODO add your handling code here:
    if(this.rdAccion.isSelected()){
        this.rdAnimada.setSelected(false);
        this.rdComedia.setSelected(false);
        this.rdDocumental.setSelected(false);
        this.rdDrama.setSelected(false);
        this.rdMusical.setSelected(false);
        this.genero = GeneroPelicula.ACCION;
    }
}//GEN-LAST:event_rdAccionStateChanged

private void rdMusicalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdMusicalStateChanged
// TODO add your handling code here:
    if(this.rdMusical.isSelected()){
        this.rdAccion.setSelected(false);
        this.rdComedia.setSelected(false);
        this.rdDocumental.setSelected(false);
        this.rdDrama.setSelected(false);
        this.rdAnimada.setSelected(false);
        this.genero = GeneroPelicula.MUSICAL;
    }
}//GEN-LAST:event_rdMusicalStateChanged

private void rdDocumentalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdDocumentalStateChanged
// TODO add your handling code here:
    if(this.rdDocumental.isSelected()){
        this.rdAccion.setSelected(false);
        this.rdComedia.setSelected(false);
        this.rdAnimada.setSelected(false);
        this.rdDrama.setSelected(false);
        this.rdMusical.setSelected(false);
        this.genero = GeneroPelicula.DOCUMENTAL;
    }
}//GEN-LAST:event_rdDocumentalStateChanged

private void rdComediaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdComediaStateChanged
// TODO add your handling code here:
    if(this.rdComedia.isSelected()){
        this.rdAccion.setSelected(false);
        this.rdAnimada.setSelected(false);
        this.rdDocumental.setSelected(false);
        this.rdDrama.setSelected(false);
        this.rdMusical.setSelected(false);
        this.genero = GeneroPelicula.COMEDIA;
    }
}//GEN-LAST:event_rdComediaStateChanged

private void rdTodosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdTodosStateChanged
// TODO add your handling code here:
    if(this.rdTodos.isSelected()){
        this.rd15.setSelected(false);
        this.rd18.setSelected(false);
        this.rdAdultos.setSelected(false);
        this.clas = TipoClasificacion.TODO_PUBLICO;
    }
}//GEN-LAST:event_rdTodosStateChanged

private void rd18StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rd18StateChanged
// TODO add your handling code here:
     if(this.rd18.isSelected()){
        this.rd15.setSelected(false);
        this.rdTodos.setSelected(false);
        this.rdAdultos.setSelected(false);
        this.clas = TipoClasificacion.MAYORES_18;
    }
}//GEN-LAST:event_rd18StateChanged

private void rd15StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rd15StateChanged
// TODO add your handling code here:
     if(this.rd15.isSelected()){
        this.rdTodos.setSelected(false);
        this.rd18.setSelected(false);
        this.rdAdultos.setSelected(false);
        this.clas = TipoClasificacion.MAYORES_15;
    }
}//GEN-LAST:event_rd15StateChanged

private void rdAdultosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdAdultosStateChanged
// TODO add your handling code here:
     if(this.rdAdultos.isSelected()){
        this.rd15.setSelected(false);
        this.rd18.setSelected(false);
        this.rdTodos.setSelected(false);
        this.clas = TipoClasificacion.ADULTOS;
    }
}//GEN-LAST:event_rdAdultosStateChanged

private void cb2DStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb2DStateChanged
// TODO add your handling code here:
    if(this.cb2D.isSelected())
        this.cb3D.setSelected(false);
    this.tipo = TipoPelicula.PELICULA2D;
            
}//GEN-LAST:event_cb2DStateChanged

private void cb3DStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cb3DStateChanged
// TODO add your handling code here:
    if(this.cb3D.isSelected())
        this.cb2D.setSelected(false);
    this.tipo = TipoPelicula.PELICULA3D;
}//GEN-LAST:event_cb3DStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            duracion = Integer.parseInt(txtDuracion.getText());
            nombre = txtNombre.getText();
            
            Pelicula peli;
            if(tipo == TipoPelicula.PELICULA2D){
                peli = new Pelicula2D(duracion, nombre, genero, clas);
            }else{
                peli = new Pelicula3D(duracion, nombre, genero, clas);
            }
            
            if(nombre == null || tipo == null || genero == null
                    || clas == null)
                throw new NullPointerException();
            
            this.peliculas.add(peli);
            
            this.setVisible(false);
            
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "No ingreso enteros en el campo de la duracion");
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(this, "Falta informacion");
        }catch(Exception ex){
            System.out.println("Un error esta impidiendo que la pelicula se agregue");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AgregarPelicula().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb2D;
    private javax.swing.JCheckBox cb3D;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rd15;
    private javax.swing.JRadioButton rd18;
    private javax.swing.JRadioButton rdAccion;
    private javax.swing.JRadioButton rdAdultos;
    private javax.swing.JRadioButton rdAnimada;
    private javax.swing.JRadioButton rdComedia;
    private javax.swing.JRadioButton rdDocumental;
    private javax.swing.JRadioButton rdDrama;
    private javax.swing.JRadioButton rdMusical;
    private javax.swing.JRadioButton rdTodos;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
